logging:
  pattern:
    level: '%5p [${spring.properties.name:},%X{traceId:-},%X{spanId:-}]'
server:
  port: 9100
  servlet:
    context-path: ${CONTEXT_PATH:/api/v1}
spring:
  application:
    name: caju-transaction
  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 50
        one-indexed-parameters: false
        page-parameter: page
        size-parameter: size
      sort:
        sort-parameter: sort
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${DATASOURCE_PASSWORD:210683}
    url: jdbc:mysql://localhost:3306/caju-auth-server?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
    username: root
  jackson:
    deserialization:
      fail-on-unknown-properties: false
    serialization:
      fail_on_empty_beans: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: ${JPA_SHOW_SQL:false}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:9000/api/v1}
          jwk-set-uri: ${JWT_JWK_URI:http://localhost:9000/api/v1/oauth2/jwks}




